name: Crawl

on:
  schedule:
  # 20+9:40 = 5:40 every day
  - cron:  '40 20 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: "1.18.0"

    - name: Print Golang version
      run: go version

    - name: Change directory and run crawler
      env:
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        cd crawler
        go run main.go
