name: Crawl

on: 
  schedule:
  # 20+9:40 = 5:40 every day
  - cron:  '40 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup golang
      run: |
        wget https://go.dev/dl/go1.18.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.18.linux-amd64.tar.gz
        go version

    - name: Run crawler
      env: 
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: go crawler/main.go
